### ISSUE TITLE
Ligand-receptor pairing for the interactions

### ISSUE THREAD

**Issue by zionjeong** [daskelly/CellReports_2018_heart_scRNAseq#1]
First of all, thank you for sharing your bioinformatic analysis details.

I'm trying to analyze cell-cell interactions using my own single-cell RNA seq data.
following your descriptions, I got matrices indicating expression of receptor/ligand in each cell clusters.
However, the 'interactions' by function tcrossprod had no value, maybe because the ligand-receptor pairing information was missing.. I used two separated vectors of genes for receptor_genes and ligand_genes, each, and the pairing information was not used at all; and maybe this is wrong..

Could you please give me some advice to solve this problem? Thanks in advance!

**Comment by daskelly** [comment]
Hi, I have changed some of the text and code in that section to clarify how the receptor/ligand data should be used. I think it should be clearer now. The way the pairing information is used is that elements 1, 2, ..., N of the vectors of receptor genes and ligand genes represent receptor-ligand pairs.
