### ISSUE TITLE
umap information is missing

### ISSUE THREAD

**Issue by Sijaz1** [daskelly/CellReports_2018_heart_scRNAseq#2]
Hi 
can you please  provide the umap information?
Thanks

**Comment by daskelly** [comment]
Hello,
This paper was published in early 2018 before the UMAP algorithm was released so we did not visualize the data using UMAP for this work. Of course it would be perfectly fine to run UMAP on the data now using your tool of choice.
Best wishes

**Comment by daskelly** [comment]
For completeness I have added the t-SNE coordinates used in the manuscript here: https://github.com/daskelly/CellReports_2018_heart_scRNAseq/blob/master/tsne.tsv

**Comment by Sijaz1** [comment]
Hi,
Thank you for your fast response.


Best Wishes,
Sadaf Ijaz

PhD Student in Karmann Lab,
Group member in Translational Data Science,
Department for Renal and Hypertensive Diseases,
Rheumatological and Immunological Diseases
(Medical Clinic II)
Uniklinik RWTH Aachen, Germany
***@***.******@***.***>





From: Dan Skelly ***@***.***>
Date: Tuesday, 16. July 2024 at 17:26
To: daskelly/CellReports_2018_heart_scRNAseq ***@***.***>
Cc: Ijaz, Sadaf ***@***.***>, Author ***@***.***>
Subject: Re: [daskelly/CellReports_2018_heart_scRNAseq] umap information is missing (Issue #2)

For completeness I have added the t-SNE coordinates used in the manuscript here: https://github.com/daskelly/CellReports_2018_heart_scRNAseq/blob/master/tsne.tsv
